# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.0
_src_path: gh:quickplates/meta
accountname: quickplates
description: React app template ⚛️
example: true
exampleaccountname: quickplates
exampledescription: React app example ⚛️
examplereponame: react-example
reponame: react
repourl: https://github.com/quickplates/react
type: app
